// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkhkwthiskzqvdylxpdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFraGt3dGhpc2t6cXZkeWx4cGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MjIwNTEsImV4cCI6MjA1ODM5ODA1MX0.QPPoRH3Ae88sSQg03Ivk9v0L-6LYEq54Z1zWFlXH2sY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);